CREATE TABLE [dbo].[TELEFONE_TIPO]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TIPO] VARCHAR(10) NOT NULL
);

CREATE TABLE [dbo].[TELEFONE]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NUMERO] INT NOT NULL,
    [DDD] INT NOT NULL,
    [TIPO] INT NOT NULL,
    CONSTRAINT [FK_TELEFONE_TIPO] FOREIGN KEY ([TIPO]) REFERENCES [TELEFONE_TIPO]([ID])
);

CREATE TABLE [dbo].[ENDERECO]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LOGRADOURO] VARCHAR(256) NOT NULL,
    [NUMERO] INT NOT NULL,
    [CEP] INT NOT NULL,
    [BAIRRO] VARCHAR(50) NOT NULL,
    [CIDADE] VARCHAR(30) NOT NULL,
    [ESTADO] VARCHAR(20) NOT NULL
);

CREATE TABLE [dbo].[PESSOA]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(256) NOT NULL,
    [CPF] BIGINT,
    [ENDERECO] INT,
    CONSTRAINT [FK_PESSOA_ENDERECO] FOREIGN KEY ([ENDERECO]) REFERENCES [ENDERECO]([ID])
);

CREATE TABLE [dbo].[PESSOA_TELEFONE]
(
	[ID_PESSOA] INT NOT NULL, 
    [ID_TELEFONE] INT NOT NULL,
    PRIMARY KEY([ID_PESSOA], [ID_TELEFONE]),
    CONSTRAINT [FK_PESSOA_TELEFONE_PESSOA] FOREIGN KEY ([ID_PESSOA]) REFERENCES [PESSOA]([ID]),
    CONSTRAINT [FK_PESSOA_TELEFONE_TELEFONE] FOREIGN KEY ([ID_TELEFONE]) REFERENCES [TELEFONE]([ID])
);